x= float(input("Ingrese un numero: "))
y= float(input("Ingrese otro numero: "))
igual= (x==y)
diferente= (x!=y)
mayor= (x>y)
menor= (x<y)
mayor_igual= (x>=y)
menor_igual= (x<=y)
print(f"Los numeros son iguales: {igual}")
print(f"Los numeros son diferentes: {diferente}")
print(f"El primer numero es mayor que el segundo: {mayor}")
print(f"El primer numero es menor que el segundo: {menor}")
print(f"El primer numero es mayor o igual que el segundo: {mayor_igual}")
print(f"El primer numero es menor o igual que el segundo: {menor_igual}")
